model = "gpt-5.5"
model_reasoning_effort = "xhigh"
personality = "pragmatic"
# service_tier = "default"
approval_policy = "never"
sandbox_mode = "danger-full-access"
default_permissions = "project-edit"

[permissions.project-edit]
extends = ":worspace"
description = "Редактирование проекта с защитой секретов"

[permissions.project-edit.filesystem."workspace_roots"]
"." = "write"
"**/*.env" = "deny"
"**/*credential*" = "deny"
"**/*secret*" = "deny"

[permissions.project-edit.worspace_roots]
"~/code/app" = true
"~/code/shared-libs" = true

[permissions.project-edit.filesystem]
":minimal" = "read"

[permissions.project-edit.filesystem."workspace_roots"]
"." = "write"
".devcontainer" = "read"
"**/*.env" = "deny"



notify = [ "C:\\Users\\user\\AppData\\Local\\OpenAI\\Codex\\runtimes\\cua_node\\789504f803e82e2b\\bin\\node_modules\\@oai\\sky\\bin\\windows\\codex-computer-use.exe", "turn-ended" ]

[windows]
sandbox = "elevated"

[plugins."github@openai-curated"]
enabled = true

[plugins."browser@openai-bundled"]
enabled = true

[projects.'C:\Users\user\repos\bughouse']
trust_level = "trusted"

[projects.'c:\users\user\.codex']
trust_level = "trusted"

[projects.'c:\users\user']
trust_level = "trusted"

[projects.'c:\users\user\desktop\test']
trust_level = "trusted"

[marketplaces.openai-bundled]
last_updated = "2026-06-17T07:52:18Z"
source_type = "local"
source = '\\?\C:\Users\user\.codex\.tmp\bundled-marketplaces\openai-bundled'

[features]
js_repl = false

[mcp_servers.node_repl]
args = []
command = 'C:\Users\user\AppData\Local\OpenAI\Codex\runtimes\cua_node\789504f803e82e2b\bin\node_repl.exe'
startup_timeout_sec = 120

[mcp_servers.node_repl.env]
NODE_REPL_NATIVE_PIPE_CONNECT_TIMEOUT_MS = "1000"
NODE_REPL_NODE_MODULE_DIRS = 'C:\Users\user\AppData\Local\OpenAI\Codex\runtimes\cua_node\789504f803e82e2b\bin\node_modules'
NODE_REPL_NODE_PATH = 'C:\Users\user\AppData\Local\OpenAI\Codex\runtimes\cua_node\789504f803e82e2b\bin\node.exe'
NODE_REPL_TRUSTED_CODE_PATHS = 'C:\Users\user\.codex'
CODEX_HOME = 'C:\Users\user\.codex'
NODE_REPL_TRUSTED_BROWSER_CLIENT_SHA256S = "89809670b247cbaffbc4f87d9fa9742a9038c0f4a06fb822d7f85ff19bf24215,bdc61752e0f9d9b1e73e3cba25ca71d3d9fe54d335ed8196378106081474d7c1"
BROWSER_USE_AVAILABLE_BACKENDS = "chrome,iab"
NODE_REPL_INSTRUCTIONS_USE_CASE_BROWSER = "Control the in-app browser in conjunction with the Browser Plugin."
NODE_REPL_INSTRUCTIONS_USE_CASE_CHROME = "Control the Chrome browser in conjunction with the Chrome Plugin. Prefer this method of controlling Chrome over alternatives (such as Computer Use) unless the user explicitly mentions an alternative."
BROWSER_USE_CODEX_APP_BUILD_FLAVOR = "prod"
BROWSER_USE_CODEX_APP_VERSION = "26.609.71450"
SKY_CUA_NATIVE_PIPE = "1"
SKY_CUA_NATIVE_PIPE_DIRECTORY = '\\.\pipe\codex-computer-use-b31e2984-75d4-45fa-b7c1-af12d2404685'
CODEX_CLI_PATH = 'C:\Users\user\AppData\Local\OpenAI\Codex\bin\f1c7ee7a13db5fed\codex.exe'
