model = "gpt-6-astra"
model_reasoning_effort = "xhigh"
personality = "pragmatic"

approval_policy = "never"
sandbox_mode = "danger-full-access"

service_tier = "default"

notify = [ "C:\\Users\\user\\AppData\\Local\\OpenAI\\Codex\\runtimes\\cua_node\\e7fe122ad3cbcd58\\bin\\node_modules\\@oai\\sky\\bin\\windows\\codex-computer-use.exe", "turn-ended" ]
[agents]
enabled = true
default_subagent_model = "gpt-5.6-terra"
default_subagent_reasoning_effort = "medium"
max_concurrent_threads_per_session = 4
interrupt_message = false

[windows]
sandbox = "elevated"

[plugins."github@openai-curated"]
enabled = true

[plugins."browser@openai-bundled"]
enabled = true

[plugins."codex-app-tools@openai-bundled"]
enabled = true

[plugins."visualize@openai-bundled"]
enabled = true

[plugins."computer-use@openai-bundled"]
enabled = true

[plugins."documents@openai-primary-runtime"]
enabled = true

[plugins."pdf@openai-primary-runtime"]
enabled = true

[plugins."spreadsheets@openai-primary-runtime"]
enabled = true

[plugins."presentations@openai-primary-runtime"]
enabled = true

[plugins."template-creator@openai-primary-runtime"]
enabled = true

[plugins."unified-computer-use@openai-bundled"]
enabled = true

[projects.'C:\Users\user\repos\bughouse']
trust_level = "trusted"

[projects.'c:\users\user\.codex']
trust_level = "trusted"

[projects.'c:\users\user']
trust_level = "trusted"

[projects.'c:\users\user\desktop\test']
trust_level = "trusted"

[projects.'c:\users\user\repos\opener']
trust_level = "trusted"

[projects.'c:\users\user\desktop\rag']
trust_level = "trusted"

[projects.'c:\users\user\documents\codex\2026-08-26\new-chat']
trust_level = "trusted"

[projects.'c:\users\user\documents\codex\2026-08-29\new-chat']
trust_level = "trusted"

[projects.'c:\users\user\documents\codex\2026-08-30\new-chat']
trust_level = "trusted"

[projects.'c:\users\user\documents\codex\2026-09-02\new-chat']
trust_level = "trusted"

[projects.'c:\users\user\documents\codex\2026-09-02\c-users-user-desktop-data-powerbi']
trust_level = "trusted"

[projects.'c:\users\user\documents\codex\2026-09-05\new-chat']
trust_level = "trusted"

[projects.'c:\users\user\desktop\аис\тестирование']
trust_level = "trusted"

[projects.'c:\users\user\minecraft']
trust_level = "trusted"

[projects.'c:\users\user\documents\codex\2026-09-06\realtime-voice-chat']
trust_level = "trusted"

[marketplaces.openai-bundled]
source_type = "local"
source = '\\?\C:\Users\user\.codex\.tmp\bundled-marketplaces\openai-bundled'

[marketplaces.openai-primary-runtime]
source_type = "local"
source = '\\?\C:\Users\user\.cache\codex-runtimes\codex-primary-runtime\plugins\openai-primary-runtime'

[features]
js_repl = false

[mcp_servers.node_repl]
args = []
command = 'C:\Users\user\AppData\Local\OpenAI\Codex\runtimes\cua_node\e7fe122ad3cbcd58\bin\node_repl.exe'
startup_timeout_sec = 120

[mcp_servers.node_repl.env]
NODE_REPL_NATIVE_PIPE_CONNECT_TIMEOUT_MS = "1000"
NODE_REPL_NODE_MODULE_DIRS = 'C:\Users\user\AppData\Local\OpenAI\Codex\runtimes\cua_node\e7fe122ad3cbcd58\bin\node_modules'
NODE_REPL_NODE_PATH = 'C:\Users\user\AppData\Local\OpenAI\Codex\runtimes\cua_node\e7fe122ad3cbcd58\bin\node.exe'
NODE_REPL_TRUSTED_CODE_PATHS = 'C:\Users\user\.codex;C:\Users\user\AppData\Local\OpenAI\Codex\runtimes\cua_node\e7fe122ad3cbcd58\bin\node_modules'
CODEX_HOME = 'C:\Users\user\.codex'
BROWSER_USE_AVAILABLE_BACKENDS = "chrome,iab"
BROWSER_USE_TINYSKY_ENABLED = "1"
NODE_REPL_INSTRUCTIONS_USE_CASE_BROWSER = ""
NODE_REPL_INSTRUCTIONS_USE_CASE_CHROME = ""
BROWSER_USE_CODEX_APP_BUILD_FLAVOR = "prod"
BROWSER_USE_CODEX_APP_VERSION = "26.903.71938"
NODE_REPL_TRUSTED_SERVICES = '{"browser":"C:/Users/user/.codex/plugins/cache/openai-bundled/browser/26.903.71938/scripts/browser-service.mjs","sky":"@oai/sky/service"}'
SKY_CUA_NATIVE_PIPE = "1"
SKY_CUA_NATIVE_PIPE_DIRECTORY = '\\.\pipe\codex-computer-use-d93d8cb2-add9-4284-8e14-593af8a291cb'
CODEX_CLI_PATH = 'C:\Users\user\AppData\Local\OpenAI\Codex\bin\7ac07f4ce733f89a\codex.exe'

[desktop]
followUpQueueMode = "queue"
localeOverride = "ru-RU"
ambient-suggestions-enabled = false
show-context-window-usage = true
conversationDetailMode = "STEPS_COMMANDS"
